spring.application.name=OAuthProject


# Google OAuth2 Configuration
spring.security.oauth2.client.registration.google.client-id=



spring.security.oauth2.client.registration.google.client-secret=


spring.security.oauth2.client.registration.google.scope=openid,profile,email

spring.security.oauth2.client.registration.google.redirect-uri={baseUrl}/login/oauth2/code/{registrationId}

spring.security.oauth2.client.registration.google.client-name=Google
